routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect("/dashboard");
});

Route::get('/home', function () {
    return redirect("/dashboard");
});

Route::get('dashboard', 'AdminController@index')->name('admin');

Auth::routes();

// setea ruta formulario login
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard'],function(){ 
    Route::get('profile','Users\UsersController@profile')->name('users.profile');
    Route::post('profile/update','Users\UsersController@save_profile')->name('users.profile.update');
});

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard/admin'],function(){  
    Route::resource('roles', 'Roles\RolesController');
    Route::put('roles/ajax/edit','Roles\RolesController@edit')->name('roles.ajax.edit');
    Route::put('roles/ajax/update','Roles\RolesController@update')->name('roles.ajax.update');
    Route::put('roles/ajax/delete','Roles\RolesController@destroy')->name('roles.ajax.delete');
    Route::resource('users', 'Users\UsersController');
    Route::put('users/ajax/edit','Users\UsersController@edit')->name('users.ajax.edit');
    Route::put('users/ajax/update','Users\UsersController@update')->name('users.ajax.update');
    Route::put('users/ajax/delete','Users\UsersController@destroy')->name('users.ajax.delete');
    Route::post('image-view','Users\UsersController@image_store');
    Route::get('avatar/{id}','Users\UsersController@avatar')->name('users.avatar');
    Route::get('configurations','Config\ConfigController@index')->name('configurations');
    Route::put('configurations/ajax/update','Config\ConfigController@update')->name('configurations.ajax.update');
    Route::put('configurations/ajax/updatePayments','Config\ConfigController@updatePayments')->name('configurations.ajax.updatePayments');
    Route::get('configurations/avatar/{id}','Config\ConfigController@avatar')->name('configurations.avatar');
    Route::put('configurations/ajax/exec/payments/process','Config\ConfigController@exec_payments_process')->name('configurations.ajax.exec_payments_process');
    Route::put('configurations/ajax/exec/overdue/payments/process','Config\ConfigController@exec_overdue_payments_process')->name('configurations.ajax.exec_overdue_payments_process');    
    Route::put('configurations/ajax/exec/instructors/payment/process','Config\ConfigController@exec_instructors_payment_process')->name('configurations.ajax.exec_instructors_payment_process');    
    Route::resource('services', 'Services\ServicesController');
    Route::put('services/ajax/edit','Services\ServicesController@edit')->name('services.ajax.edit');
    Route::put('services/ajax/update','Services\ServicesController@update')->name('services.ajax.update');
    Route::put('services/ajax/delete','Services\ServicesController@destroy')->name('services.ajax.delete');
    Route::put('services/ajax/types','Services\ServicesController@get_tbl_types')->name('services.ajax.table_types');
    Route::put('services/ajax/types/store','Services\ServicesController@store_type')->name('services.ajax.store_type');    
    Route::put('services/ajax/levels','Services\ServicesController@get_tbl_levels')->name('services.ajax.table_levels'); 
    Route::put('services/ajax/levels/store','Services\ServicesController@store_level')->name('services.ajax.store_level');
    Route::put('services/ajax/update/status','Services\ServicesController@update_status')->name('services.ajax.update_status');    
    Route::put('services/ajax/delete/type/level','Services\ServicesController@delete_type_or_level')->name('services.ajax.delete_type_or_level');    
    Route::resource('students','Students\StudentsController');
    Route::put('students/ajax/edit','Students\StudentsController@edit')->name('students.ajax.edit');
    Route::put('students/ajax/update','Students\StudentsController@update')->name('students.ajax.update');
    Route::put('students/ajax/delete','Students\StudentsController@destroy')->name('students.ajax.delete');
    Route::resource('instructors','Instructors\InstructorsController');
    Route::put('instructors/ajax/edit','Instructors\InstructorsController@edit')->name('instructors.ajax.edit');
    Route::put('instructors/ajax/update','Instructors\InstructorsController@update')->name('instructors.ajax.update');
    Route::put('instructors/ajax/delete','Instructors\InstructorsController@destroy')->name('instructors.ajax.delete');     
    Route::resource('courses','Courses\CoursesController');
    Route::put('courses/ajax/edit','Courses\CoursesController@edit')->name('courses.ajax.edit');
    Route::put('courses/ajax/update','Courses\CoursesController@update')->name('courses.ajax.update');
    Route::put('courses/ajax/delete','Courses\CoursesController@destroy')->name('courses.ajax.delete');
    Route::put('courses/ajax/calcule/time','Courses\CoursesController@update_end_time')->name('courses.ajax.update_end_time');
    Route::put('inscriptions/ajax/index','Inscriptions\InscriptionsController@index')->name('inscriptions.ajax.index');
    Route::put('inscriptions/ajax/edit','Inscriptions\InscriptionsController@edit')->name('inscriptions.ajax.edit');
    Route::put('inscriptions/ajax/update','Inscriptions\InscriptionsController@update')->name('inscriptions.ajax.update');
    Route::put('inscriptions/ajax/delete','Inscriptions\InscriptionsController@destroy')->name('inscriptions.ajax.delete');
    Route::put('inscriptions/ajax/student','Inscriptions\InscriptionsController@info_student')->name('inscriptions.ajax.info_student');
    Route::put('inscriptions/ajax/student/inscribe','Inscriptions\InscriptionsController@inscribe')->name('inscriptions.ajax.inscribe');
    Route::put('inscriptions/ajax/table/registration','Inscriptions\InscriptionsController@table_registration')->name('inscriptions.ajax.table_registration');
    //payments
    Route::get('payments','Payments\PaymentsController@index')->name('payments.index'); 
    Route::put('payments/courses','Payments\PaymentsController@get_courses_student')->name('payments.ajax.get_courses_student');
    Route::put('payments/info/course','Payments\PaymentsController@info_course')->name('payments.ajax.info_course');
    Route::put('payments/save','Payments\PaymentsController@store')->name('payments.ajax.store');    
    Route::put('payments/total','Payments\PaymentsController@get_total')->name('payments.ajax.get_total');    
    Route::put('payments/add/payment','Payments\PaymentsController@add_new_payment')->name('payments.ajax.add_new_payment');    
    Route::put('payments/add/payment/courses','Payments\PaymentsController@get_courses_student_new_payment')->name('payments.ajax.get_courses_student_new_payment');    
    Route::put('payments/add/payment/courses/cash/value','Payments\PaymentsController@info_value_cash_new_payment')->name('payments.ajax.info_value_cash_new_payment');        
    Route::put('payments/save/payment','Payments\PaymentsController@store_new_payment')->name('payments.ajax.store_new_payment');             
    Route::get('payments/view/all/','Payments\PaymentsController@index_payments')->name('payments.index_payments'); 
    Route::get('payments/export/excel/{status?}/{concept?}/{start_date?}/{end_date?}','Payments\PaymentsController@export_excel')->name('payments.export.excel');     
    //jobs
    Route::get('jobs/process/payments/monthly_payments','Jobs\JobsController@monthly_payments_process')->name('jobs.monthly_payments_process'); 
    Route::get('files/display/{id}','Users\UsersController@display_file')->name('display_file'); 
});

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard/student'],function(){    
    Route::get('courses','Students\StudentsController@my_courses')->name('students.my_courses');
    Route::get('payments','Students\StudentsController@my_payments')->name('students.my_payments');
    Route::post('paypal/payment','Payments\Paypal\PaypalController@paypal_payment')->name('students.paypal_payment');
    Route::get('paypal/payment/status','Payments\Paypal\PaypalController@paypal_payment_status')->name('students.paypal_payment_status');
});

app/Models/Role.php
<?php
/**
 * Created by Reliese Model.
 * Date: Sat, 12 May 2018 21:06:21 +0000.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;
use Caffeinated\Shinobi\Concerns\HasRolesAndPermissions;

/**
 * Class AppParameter
 *
 * @property int $ParameterID
 * @property string $strParent
 * @property string $strValue
 *
 * @package App\Models
 */
class Role extends Model implements Auditable
{
        use \OwenIt\Auditing\Auditable;
        use HasRolesAndPermissions;
        
	protected $primaryKey = 'id';
        protected $table = 'roles';
	public $incrementing = true;
	public $timestamps = true;

	protected $casts = [
		'id' => 'int'
	];

	protected $fillable = [
		'name',
                'slug',
		'description',
		'special',
		'is_admin'
	];
        
        public function generateTags():array{
            return['roles'];
        }//generateTag
}

resources/views/admin/roles/create.blade.php
<style>
  .project-tab #tabs .nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active {
    color: #0062cc;
    border-bottom: 3px solid !important;
    font-size: 16px;
    font-weight: bold;
  }
</style>
<div class="row">
    <div class="col-md-12">
       
      
            <form  id="createForm" method="post" action="{{route('roles.store')}}">
            {{csrf_field()}}
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label for="name" class="control-label">{{trans('adminlte::adminlte.name')}}(*)</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="{{trans('adminlte::adminlte.name')}}">
                    </div>
                </div>

                <div class="form-group">
                  <label for="description" class="control-label">{{trans('adminlte::adminlte.description')}}</label>
                    <textarea id="description" class="form-control" rows="3" maxlength="255" name="description"></textarea>
                </div>


                <div class="clearfix">
                    <h5 class="box-title">{{trans('adminlte::roles.permissions')}}</h5>
                </div>

            
                <div class="row">

                  <div class="col-6 col-sm-6">
                    <div class="nav flex-column nav-tabs h-100" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
                    
                      @foreach(config('permits.modules') as $module)
                      <a class="nav-link @if(array_key_exists('activeTab',$module)) active @endif" id="vert-tabs-{{trans($module['module'])}}-tab" data-toggle="pill" href="#vert-tabs-{{trans($module['module'])}}" role="tab" aria-controls="vert-tabs-{{trans($module['module'])}}" aria-selected="false">{{trans($module['module'])}}</a>
                      @endforeach
                    
                    </div>
                  </div>

                  <div class="col-6 col-sm-6">
                    <div class="tab-content" id="vert-tabs-tabContent">


                        @foreach(config('permits.modules') as $module)
                          <div class="tab-pane fade @if(array_key_exists('activeTab',$module)) show active @endif" id="vert-tabs-{{trans($module['module'])}}" role="tabpanel" aria-labelledby="vert-tabs-{{trans($module['module'])}}-  -tab">
                            
                            <!-- Minimal style -->
                            <div class="row">
                              <div class="col-sm-6">

                          
                                  <!-- checkbox -->
                                  <div class="form-group clearfix">
                                          <div class="icheck-primary d-inline">
                                              <input type="checkbox" name="checkall-{{$module['slug']}}" id="checkall-{{$module['slug']}}" value="" class="checkall" data-rel="vert-tabs-{{trans($module['module'])}}">
                                              <label for="checkall-{{$module['slug']}}">
                                              {{trans('adminlte::adminlte.all')}}
                                              </label>
                                          </div>
                                      </div>
                                  @if(array_key_exists('slugs',$module))
                                                        
                                    @php
                                    if(is_array($module['slugs'])){
                                        $module_slugs = $module['slugs'];
                                    }else{
                                    eval('$module_slugs = '.$module['slugs'].';');
                                    }
                                    @endphp

                                    @foreach($module_slugs as $slug)
                                      <!-- checkbox -->
                                      <div class="form-group clearfix">
                                          <div class="icheck-primary d-inline">
                                              <input type="checkbox" name="permits[{{$slug['slug']}}]" id="permits-{{$slug['slug']}}" value="{{$slug['slug']}}">
                                              <label for="permits-{{$slug['slug']}}">
                                              {{trans($slug['display'])}}
                                              </label>
                                          </div>
                                      </div>
                                    @endforeach
                                  @endif
                                
                              </div>
                            </div>

                          </div>
                        @endforeach
                      

                    </div>
                  </div>

                </div>
        

            </div>

            </form>
        






    </div>



       
</div>

@section('js')
<script type="text/javascript">
    $(function(){

      var checkAll = $('input.checkall');

      $(".checkall").click(function(){
          $('#'+$(this).data('rel')).children().find("input[type=checkbox]").prop('checked', this.checked);
      });
  
    });
</script>
@stop

resources/views/admin/roles/index.blade.php
@extends('adminlte::page')

@section('title',trans('adminlte::roles.roles'))

@section('content_header')
<div class="row mb-2">
    <div class="col-sm-6">
        <h1>
            <i class="fa fa-unlock-alt" style="margin:10px 10px 10px 10px;"></i>
            {{trans('adminlte::roles.roles')}}
        </h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            
            <li class="breadcrumb-item"><a href="{{route('admin')}}">{{trans('adminlte::adminlte.administration')}}</a></li>
            <li class="breadcrumb-item active">{{trans('adminlte::roles.roles')}}</li>
        </ol>
    </div>
</div>

@stop


@section('content')

    <div class="card">
        <div class="card-header">
          <div class="card-title">
          @if($permits['create'])<a href="#" class="btn btn-block btn-success btnModalCreate" data-toggle="modal">Crear</a>@endif
          </div>
        </div>

        <div class="card-body">          
            {!! $html->table(['class' => 'table table-striped dt-responsive', 'style' => 'width:100%']) !!}
        </div>

        <!-- /.card-body -->
        <div class="card-footer"></div>
        <!-- /.card-footer-->
    </div>


    <div class="modal fade" id="modal-create-rol" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-info disabled color-palette">
                <h5 class="modal-title" id="myModalLabelCreate"><i class="fa fa-unlock-alt"></i> Crear Rol</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body">

            <div class="container-fluid">
                    <div id="content-create-rol"></div>
                    </div>               
            </div>
        <div class="modal-footer">
            
            <div class="w-100">
                <button type="button" class="btn btn-secondary float-left" data-dismiss="modal">{{trans('adminlte::adminlte.close')}}</button>
                <button type="button" id="btn-save-create-rol" name="btn-save-ceate-rol" class="btn btn-success float-right">{{trans('adminlte::adminlte.save')}}</button>
            </div>

        </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
    </div>
    

    <div class="modal fade" id="modal-edit-rol" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-info disabled color-palette">
                <h5 class="modal-title" id="myModalLabel"><i class="fa fa-unlock-alt"></i> Editar Rol</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body">

            <div class="container-fluid">
                    <div id="content-edit-rol"></div>
                    </div>               
            </div>
        <div class="modal-footer">
            
            <div class="w-100">
                <button type="button" class="btn btn-secondary float-left" data-dismiss="modal">{{trans('adminlte::adminlte.close')}}</button>
                <button type="button" id="btn-save-edit-rol" name="btn-save-edit-rol" class="btn btn-success float-right" data-target="#confirmEdit">{{trans('adminlte::adminlte.save')}}</button>
            </div>

        </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
    </div>

@stop
@section('js')

{!! $html->scripts() !!}

<script>

  $(function () {

        var checkAll = $('input.checkall');

        $(document).on('click', ".checkall", function () {
            $('#'+$(this).data('rel')).children().find("input[type=checkbox]").prop('checked', this.checked);
        });

        $(".btnModalCreate").click(function(){
            
            var _token = "{{csrf_token()}}";
            var _method = "PUT";
            var idRol = $(this).data('id');
            
            // Limpiamos modal de EDICIÓN para evitar errores de ids y clases duplicados
            $("#content-edit-rol").html('');

            $.ajax({
                headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
                url: "{{route('roles.create')}}",
                type:'GET',
                cache:false,
                data:{'_token':_token,'_method':_method},
                datatype:'html',
                beforeSend:function(){
                    $('.contaninerLoading').show();
                },
                complete: function(){
                    $('.contaninerLoading').hide(); 
                },
                success:function(data){

                  $("#content-create-rol").html(data);
                  $('#modal-create-rol').modal('show');
                
                },
                error:function(xhr,textStatus,thrownError){
                    alert(xhr + "\n" + textStatus + "\n" + thrownError);
                }
            });       
        });


        $(document).on('click', '#btn-save-create-rol', function () {
            
            let _token = "{{csrf_token()}}";
            let _method = "POST";
            let name = $('#name').val();
            let description = $('#description').val();
            let permits = [];

            $('#createForm input[type=checkbox]').each(function(){
                if (this.checked) {
                    permits.push( $(this).val() );
                }
            }); 


            $.ajax({
                headers: { 'X-CSRF-Token' : $('meta[name=_token]').attr('content') },
                url: "{{route('roles.store')}}",
                type: 'POST',
                cache: false,
                data: {
                        name:name,
                        description:description, 
                        permits:permits,
                        '_token':_token,
                        '_method':_method
                },
                datatype: 'html',
                beforeSend:function(){
                    $('.contaninerLoading').show();
                },
                complete: function(){
                    $('.contaninerLoading').hide(); 
                },
                success: function(data){

                    if(data.status == 1){
                        $('#modal-create-rol').modal('hide');
                        msgNotification(data.type, data.msg);

                        // Se refresca tabla por ajax
                        let table = $('.table').DataTable();
                        table.ajax.reload();
                    }else{
                        ctlErrorRequestAjax(data);
                    }
                },
                error: function (xhr,textStatus,thrownError) {
 
                    alert(xhr + "\n" + textStatus + "\n" + thrownError);
                }
    
            });
        
        }); 

        
        $(document).on('click', '.btnModalEdit', function(){
            
            var _token = "{{csrf_token()}}";
            var _method = "PUT";
            var idRol = $(this).data('id');
            
            // Limpiamos modal de CREACIÓN para evitar errores de ids y clases duplicados
            $("#content-create-rol").html('');


            $.ajax({
                headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
                url: "{{route('roles.ajax.edit')}}",
                type:'POST',
                cache:false,
                data:{'_id': idRol,'_token':_token,'_method':_method},
                datatype:'html',
                beforeSend:function(){
                    $('.contaninerLoading').show();
                },
                complete: function(){
                    $('.contaninerLoading').hide(); 
                },
                success:function(data){

                  
                  $("#content-edit-rol").html(data);
                  $('#modal-edit-rol').modal('show');
                
                },
                error:function(xhr,textStatus,thrownError){
                    alert(xhr + "\n" + textStatus + "\n" + thrownError);
                }
            });       
        });
  
        $(document).on('click', '#btn-save-edit-rol', function () {
            
                let _token = "{{csrf_token()}}";
                let _method = "PUT";
                let id = $("#id").val();
                let name = $('#name').val();
                let description = $('#description').val();
                let permits = [];

                $('#editForm input[type=checkbox]').each(function(){
                    if (this.checked) {
                        permits.push( $(this).val() );
                    }
                }); 


                $.ajax({
                    headers: { 'X-CSRF-Token' : $('meta[name=_token]').attr('content') },
                    url: "{{route('roles.ajax.update')}}",
                    type: 'POST',
                    cache: false,
                    data: {
                            id:id,
                            name:name,
                            description:description, 
                            permits:permits,
                            '_token':_token,
                            '_method':_method
                    },
                    datatype: 'html',
                    beforeSend:function(){
                        $('.contaninerLoading').show();
                    },
                    complete: function(){
                        $('.contaninerLoading').hide(); 
                    },
                    success: function(data){

                        if(data.status == 1){
                            $('#modal-edit-rol').modal('hide');
                            msgNotification(data.type, data.msg);

                            // Se refresca tabla por ajax
                            let table = $('.table').DataTable();
                            table.ajax.reload();

                        }else{
                            ctlErrorRequestAjax(data);
                        }
                    },
                    error: function (xhr,textStatus,thrownError) {
     
                        alert(xhr + "\n" + textStatus + "\n" + thrownError);
                    }
        
                });
        
        }); 

        // Confirm delete
        $('.deleteForm').click(function(){

            let _token = "{{csrf_token()}}";
            let _method = "PUT";
            let id = $('#idDelete').val();

            $.ajax({
                headers: { 'X-CSRF-Token' : $('meta[name=_token]').attr('content') },
                url: "{{route('roles.ajax.delete')}}",
                type: 'POST',
                cache: false,
                data: {
                        id:id,
                        '_token':_token,
                        '_method':_method
                },
                datatype: 'html',
                beforeSend:function(){
                    $('.contaninerLoading').show();
                },
                complete: function(){
                    $('.contaninerLoading').hide(); 
                },
                success: function(data){

                    if(data.status == 1){
                        $('#confirmDelete').modal('hide');
                        msgNotification(data.type, data.msg);

                        // Se refresca tabla por ajax
                        let table = $('.table').DataTable();
                        table.ajax.reload();

                    }
                },
                error: function (xhr,textStatus,thrownError) {
    
                    alert(xhr + "\n" + textStatus + "\n" + thrownError);
                }
    
            });
        });

    });

    </script>
 @stop









  