routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect("/dashboard");
});

Route::get('/home', function () {
    return redirect("/dashboard");
});

Route::get('dashboard', 'AdminController@index')->name('admin');

Auth::routes();

// setea ruta formulario login
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard'],function(){ 
    Route::get('profile','Users\UsersController@profile')->name('users.profile');
    Route::post('profile/update','Users\UsersController@save_profile')->name('users.profile.update');
});

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard/admin'],function(){  
    Route::resource('roles', 'Roles\RolesController');
    Route::put('roles/ajax/edit','Roles\RolesController@edit')->name('roles.ajax.edit');
    Route::put('roles/ajax/update','Roles\RolesController@update')->name('roles.ajax.update');
    Route::put('roles/ajax/delete','Roles\RolesController@destroy')->name('roles.ajax.delete');
    Route::resource('users', 'Users\UsersController');
    Route::put('users/ajax/edit','Users\UsersController@edit')->name('users.ajax.edit');
    Route::put('users/ajax/update','Users\UsersController@update')->name('users.ajax.update');
    Route::put('users/ajax/delete','Users\UsersController@destroy')->name('users.ajax.delete');
    Route::post('image-view','Users\UsersController@image_store');
    Route::get('avatar/{id}','Users\UsersController@avatar')->name('users.avatar');
    Route::get('configurations','Config\ConfigController@index')->name('configurations');
    Route::put('configurations/ajax/update','Config\ConfigController@update')->name('configurations.ajax.update');
    Route::put('configurations/ajax/updatePayments','Config\ConfigController@updatePayments')->name('configurations.ajax.updatePayments');
    Route::get('configurations/avatar/{id}','Config\ConfigController@avatar')->name('configurations.avatar');
    Route::put('configurations/ajax/exec/payments/process','Config\ConfigController@exec_payments_process')->name('configurations.ajax.exec_payments_process');
    Route::put('configurations/ajax/exec/overdue/payments/process','Config\ConfigController@exec_overdue_payments_process')->name('configurations.ajax.exec_overdue_payments_process');    
    Route::put('configurations/ajax/exec/instructors/payment/process','Config\ConfigController@exec_instructors_payment_process')->name('configurations.ajax.exec_instructors_payment_process');    
    Route::resource('services', 'Services\ServicesController');
    Route::put('services/ajax/edit','Services\ServicesController@edit')->name('services.ajax.edit');
    Route::put('services/ajax/update','Services\ServicesController@update')->name('services.ajax.update');
    Route::put('services/ajax/delete','Services\ServicesController@destroy')->name('services.ajax.delete');
    Route::put('services/ajax/types','Services\ServicesController@get_tbl_types')->name('services.ajax.table_types');
    Route::put('services/ajax/types/store','Services\ServicesController@store_type')->name('services.ajax.store_type');    
    Route::put('services/ajax/levels','Services\ServicesController@get_tbl_levels')->name('services.ajax.table_levels'); 
    Route::put('services/ajax/levels/store','Services\ServicesController@store_level')->name('services.ajax.store_level');
    Route::put('services/ajax/update/status','Services\ServicesController@update_status')->name('services.ajax.update_status');    
    Route::put('services/ajax/delete/type/level','Services\ServicesController@delete_type_or_level')->name('services.ajax.delete_type_or_level');    
    Route::resource('students','Students\StudentsController');
    Route::put('students/ajax/edit','Students\StudentsController@edit')->name('students.ajax.edit');
    Route::put('students/ajax/update','Students\StudentsController@update')->name('students.ajax.update');
    Route::put('students/ajax/delete','Students\StudentsController@destroy')->name('students.ajax.delete');
    Route::resource('instructors','Instructors\InstructorsController');
    Route::put('instructors/ajax/edit','Instructors\InstructorsController@edit')->name('instructors.ajax.edit');
    Route::put('instructors/ajax/update','Instructors\InstructorsController@update')->name('instructors.ajax.update');
    Route::put('instructors/ajax/delete','Instructors\InstructorsController@destroy')->name('instructors.ajax.delete');     
    Route::resource('courses','Courses\CoursesController');
    Route::put('courses/ajax/edit','Courses\CoursesController@edit')->name('courses.ajax.edit');
    Route::put('courses/ajax/update','Courses\CoursesController@update')->name('courses.ajax.update');
    Route::put('courses/ajax/delete','Courses\CoursesController@destroy')->name('courses.ajax.delete');
    Route::put('courses/ajax/calcule/time','Courses\CoursesController@update_end_time')->name('courses.ajax.update_end_time');
    Route::put('inscriptions/ajax/index','Inscriptions\InscriptionsController@index')->name('inscriptions.ajax.index');
    Route::put('inscriptions/ajax/edit','Inscriptions\InscriptionsController@edit')->name('inscriptions.ajax.edit');
    Route::put('inscriptions/ajax/update','Inscriptions\InscriptionsController@update')->name('inscriptions.ajax.update');
    Route::put('inscriptions/ajax/delete','Inscriptions\InscriptionsController@destroy')->name('inscriptions.ajax.delete');
    Route::put('inscriptions/ajax/student','Inscriptions\InscriptionsController@info_student')->name('inscriptions.ajax.info_student');
    Route::put('inscriptions/ajax/student/inscribe','Inscriptions\InscriptionsController@inscribe')->name('inscriptions.ajax.inscribe');
    Route::put('inscriptions/ajax/table/registration','Inscriptions\InscriptionsController@table_registration')->name('inscriptions.ajax.table_registration');
    //payments
    Route::get('payments','Payments\PaymentsController@index')->name('payments.index'); 
    Route::put('payments/courses','Payments\PaymentsController@get_courses_student')->name('payments.ajax.get_courses_student');
    Route::put('payments/info/course','Payments\PaymentsController@info_course')->name('payments.ajax.info_course');
    Route::put('payments/save','Payments\PaymentsController@store')->name('payments.ajax.store');    
    Route::put('payments/total','Payments\PaymentsController@get_total')->name('payments.ajax.get_total');    
    Route::put('payments/add/payment','Payments\PaymentsController@add_new_payment')->name('payments.ajax.add_new_payment');    
    Route::put('payments/add/payment/courses','Payments\PaymentsController@get_courses_student_new_payment')->name('payments.ajax.get_courses_student_new_payment');    
    Route::put('payments/add/payment/courses/cash/value','Payments\PaymentsController@info_value_cash_new_payment')->name('payments.ajax.info_value_cash_new_payment');        
    Route::put('payments/save/payment','Payments\PaymentsController@store_new_payment')->name('payments.ajax.store_new_payment');             
    Route::get('payments/view/all/','Payments\PaymentsController@index_payments')->name('payments.index_payments'); 
    Route::get('payments/export/excel/{status?}/{concept?}/{start_date?}/{end_date?}','Payments\PaymentsController@export_excel')->name('payments.export.excel');     
    //jobs
    Route::get('jobs/process/payments/monthly_payments','Jobs\JobsController@monthly_payments_process')->name('jobs.monthly_payments_process'); 
    Route::get('files/display/{id}','Users\UsersController@display_file')->name('display_file'); 
});

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard/student'],function(){    
    Route::get('courses','Students\StudentsController@my_courses')->name('students.my_courses');
    Route::get('payments','Students\StudentsController@my_payments')->name('students.my_payments');
    Route::post('paypal/payment','Payments\Paypal\PaypalController@paypal_payment')->name('students.paypal_payment');
    Route::get('paypal/payment/status','Payments\Paypal\PaypalController@paypal_payment_status')->name('students.paypal_payment_status');
});

resources/views/admin/students/create.blade.php
{{csrf_field()}}
<div class="row">        
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">        
        <ul class="nav nav-tabs" id="create-myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="student-tab" data-toggle="tab" href="#tbStudent" role="tab" aria-controls="tbStudent" aria-selected="false">{{trans('adminlte::students.infStudent')}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="tutor-tab" data-toggle="tab" href="#tabTutor" role="tab" aria-controls="tabTutor" aria-selected="false">{{trans('adminlte::students.infTutor')}}</a>
            </li>         
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tbStudent" role="tabpanel" aria-labelledby="student-tab">
                <div class="row">
                    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <label for="name" class="control-label">{{trans('adminlte::adminlte.name')}}<span class="kv-reqd">*</span></label>
                        <input type="text" id="name" class="form-control" maxlength="190" name="name" placeholder="{{trans('adminlte::adminlte.name')}}">
                    </div>
                    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <label for="lastName" class="control-label">{{trans('adminlte::students.lastName')}}</label>
                        <input type="text" id="lastName" class="form-control" maxlength="190" name="lastName" placeholder="{{trans('adminlte::students.lastName')}}">
                    </div>
                    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <label for="email" class="control-label">{{trans('adminlte::adminlte.email')}}<span class="kv-reqd">*</span></label>
                        <input type="email" id="email" class="form-control" maxlength="190" name="email" placeholder="{{trans('adminlte::adminlte.email')}}">
                    </div>
                    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <label for="phone" class="control-label">{{trans('adminlte::adminlte.phone')}}</label>
                        <input type="text" id="phone" class="form-control" maxlength="190" name="phone" placeholder="{{trans('adminlte::adminlte.phone')}}">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <label for="address" class="control-label">{{trans('adminlte::adminlte.direction')}}</label>
                        <input type="text" id="address" class="form-control" minlength="8" maxlength="190" name="address" placeholder="{{trans('adminlte::adminlte.direction')}}">
                    </div>
                    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <label for="status" class="control-label">{{trans('adminlte::adminlte.status')}}<span class="kv-reqd">*</span></label>
                        <select id="status" name="status" class="form-control select2 select2-hidden-accessible" data-placeholder="{{trans('adminlte::adminlte.status')}}" style="width: 100%;">
                            <option value=""></option>
                            <option value="1">{{trans('adminlte::adminlte.active')}}</option>
                            <option value="0">{{trans('adminlte::adminlte.inactive')}}</option>
                        </select>
                    </div>
                    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <label for="password" class="control-label">{{trans('adminlte::adminlte.password')}}<span class="kv-reqd">*</span></label>
                        <input type="password" id="password" class="form-control" minlength="8" maxlength="255" name="password" placeholder="{{trans('adminlte::adminlte.password')}}">
                    </div>
                    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <label for="password_confirmation" class="control-label">{{trans('adminlte::adminlte.confirm_password')}}<span class="kv-reqd">*</span></label>
                        <input type="password" id="password_confirmation" class="form-control" minlength="8" maxlength="255" name="password_confirmation" placeholder="{{trans('adminlte::adminlte.confirm_password')}}">
                    </div>                    
                </div>                 
            </div>
            <div class="tab-pane" id="tabTutor" role="tabpanel" aria-labelledby="tutor-tab">
                <div class="row">
                    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <label for="tutorName" class="control-label">{{trans('adminlte::students.tutorName')}}</label>
                        <input type="text" id="tutorName" class="form-control" maxlength="190" name="tutorName" placeholder="{{trans('adminlte::students.tutorName')}}">
                    </div>
                    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <label for="tutorLastName" class="control-label">{{trans('adminlte::students.tutorLastName')}}</label>
                        <input type="text" id="tutorLastName" class="form-control" maxlength="190" name="tutorLastName" placeholder="{{trans('adminlte::students.tutorLastName')}}">
                    </div>
                    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <label for="tutorEmail" class="control-label">{{trans('adminlte::students.tutorEmail')}}</label>
                        <input type="email" id="tutorEmail" class="form-control" maxlength="190" name="tutorEmail" placeholder="{{trans('adminlte::students.tutorEmail')}}">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <label for="tutorPhone" class="control-label">{{trans('adminlte::students.tutorPhone')}}</label>
                        <input type="text" id="tutorPhone" class="form-control" maxlength="190" name="tutorPhone" placeholder="{{trans('adminlte::students.tutorPhone')}}">
                    </div>
                    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <label for="tutorAddress" class="control-label">{{trans('adminlte::students.tutorAddress')}}</label>
                        <input type="text" id="tutorAddress" class="form-control" minlength="8" maxlength="190" name="tutorAddress" placeholder="{{trans('adminlte::students.tutorAddress')}}">
                    </div>
                    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <label for="relationship" class="control-label">{{trans('adminlte::students.relationship')}}</label>
                        <select id="relationship" name="relationship" class="form-control select2 select2-hidden-accessible" data-placeholder="{{trans('adminlte::students.relationship')}}" style="width: 100%;">
                            <option value=""></option>
                            @foreach(\App\Models\Kinship::where('status',1)->orderBy('name','ASC')->get() as $kinship)
                                <option value="{{$kinship->id}}">{{ $kinship->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>     
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <label for="observations" class="control-label">{{trans('adminlte::adminlte.observations')}}</label>
        <textarea id="observations" class="form-control" rows="3" maxlength="5000" name="observations"></textarea>
    </div>
</div>
@if(\App\Models\File_type::find(1)->status == 1 || \App\Models\File_type::find(2)->status == 1)
    <div class="row">    
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <table class="table table-sm table-striped table-bordered dt-responsive">
                <thead>                  
                    <tr>
                        <th>{{trans('adminlte::adminlte.file')}}</th>
                        <th><i class="fas fa-paperclip"></i></th>
                    </tr>
                </thead>
                <tbody>
                    @if(\App\Models\File_type::find(1)->status == 1)
                        <tr>
                            <td>{{trans('adminlte::students.curp')}}</td>
                            <td><input type="file" id="curp" class="form-control-file" name="curp"></td>
                        </tr>
                    @endif
                    @if(\App\Models\File_type::find(2)->status == 1)
                        <tr>
                            <td>{{trans('adminlte::students.birthCertificate')}}</td>
                            <td><input type="file" id="birthCertificate" class="form-control-file" name="birthCertificate"></td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@endif

resources/views/admin/students/index.blade.php
@extends('adminlte::page')
@section('title',trans('adminlte::students.students'))
@section('content_header')
<div class="row mb-2">
    <div class="col-sm-6">
        <h1><i class="fas fa-user-graduate " style="margin:10px 10px 10px 10px;"></i>{{trans('adminlte::students.students')}}</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">{{trans('adminlte::adminlte.administration')}}</a></li>
            <li class="breadcrumb-item active">{{trans('adminlte::students.students')}}</li>
        </ol>
    </div>
</div>
@stop
@section('content')
<div class="card">
    <div class="card-header">
        <div class="card-title">
            @if($permits['create'])
                <a href="#" class="btn btn-block btn-success btnModalCreate" data-toggle="modal">{{trans('adminlte::adminlte.create')}}</a>
            @endif
        </div>
    </div>
    <div class="card-body">
        {!! $html->table(['class' => 'table table-striped table-bordered dt-responsive table-stundents', 'style' => 'width:100%']) !!}
    </div>
</div>
<div class="modal fade" id="modal-create-student" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header bg-gradient-info disabled color-palette">
                <h5 class="modal-title"><i class="fa fa-user-friends"></i> {{trans('adminlte::students.createStudent')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form id="frm-crate-student" name="frm-crate-student" enctype="multipart/form-data">
                <div class="modal-body" id="content-create-student"></div>            
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" id="btn-save-student" name="btn-save-student" class="btn btn-success">{{trans('adminlte::adminlte.save')}}</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modal-edit-student" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header bg-gradient-info disabled color-palette">
                <h5 class="modal-title"><i class="fa fa-user-friends"></i> {{trans('adminlte::students.editStudent')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form id="frm-edit-student" name="frm-edit-student" enctype="multipart/form-data">
                <div class="modal-body" id="content-edit-student"></div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" id="btn-save-edit-student" name="btn-save-edit-student" class="btn btn-success">{{trans('adminlte::adminlte.save')}}</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@stop
@section('js')
{!! $html->scripts() !!}
<script>
_token = "{{csrf_token()}}";
_method = "PUT";
$(function () {
    
    $(".btnModalCreate").click(function(){
        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url: "{{route('students.create')}}",
            type:'GET',
            cache:false,
            data:{'_token':_token,'_method':_method},
            datatype:'JSON',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete:function(){
                $('.contaninerLoading').hide(); 
            },
            success:function(data){
                if(data.status !== 1){
                    ctlErrorRequestAjax(data);
                }//if
                else{
                    $("#content-create-student").html(data.html);
                    $('.select2').select2();
                    $('#modal-create-student').modal('show');
                }//else
            },
            error:function(xhr,textStatus,thrownError){
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });       
    });
    
    $('#frm-crate-student').submit(function(e){
        
        e.preventDefault();
        
        var formData = new FormData(this);
        
        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url:"{{route('students.store')}}",
            type:'POST',
            data:formData,
            cache:false,
            contentType: false,
            processData: false,
            datatype:'JSON',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete: function(){
                $('.contaninerLoading').hide(); 
            },
            success: function(data){                                
                if(data.status === 1){
                    $('#modal-create-student').modal('hide');
                    msgNotification(data.type, data.msg);
                    let table = $('.table-stundents').DataTable();
                    table.ajax.reload();
                }else{
                    ctlErrorRequestAjax(data);
                }
            },
            error: function (xhr,textStatus,thrownError) {
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });
    }); 

    $(document).on('click','.btnModalEdit',function(){

        var _token = "{{csrf_token()}}";
        var _method = "PUT";
        var id = $(this).data('id');

        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url: "{{route('students.ajax.edit')}}",
            type:'POST',
            cache:false,
            data:{'_id':id,'_token':_token,'_method':_method},
            datatype:'html',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete: function(){
                $('.contaninerLoading').hide(); 
            },
            success:function(data){
                $("#content-edit-student").html(data);
                $('.select2').select2();
                $('#modal-edit-student').modal('show');
            },
            error:function(xhr,textStatus,thrownError){
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });       
    });

    //$(document).on('click','#btn-save-edit-student',function (){
    $('#frm-edit-student').submit(function(e){
        
        e.preventDefault();
        
        var formData = new FormData(this);
        
        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url:"{{route('students.ajax.update')}}",
            type:'POST',
            data:formData,
            cache:false,
            contentType: false,
            processData: false,
            datatype:'JSON',
            beforeSend:function(){
            $('.contaninerLoading').show();
            },
            complete: function(){
            $('.contaninerLoading').hide(); 
            },
            success: function(data){
                if(data.status === 1){
                    $('#modal-edit-student').modal('hide');
                    msgNotification(data.type,data.msg);
                    let table = $('.table-stundents').DataTable();
                    table.ajax.reload();
                }
                else{
                    ctlErrorRequestAjax(data);
                }
            },
            error: function (xhr,textStatus,thrownError) {
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });
    }); 
    
    // Confirm delete
    $('.deleteForm').click(function(){

        let _token = "{{csrf_token()}}";
        let _method = "PUT";
        let id = $('#idDelete').val();

        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content') },
            url: "{{route('students.ajax.delete')}}",
            type: 'POST',
            cache: false,
            data:{id:id,'_token':_token,'_method':_method},
            datatype: 'JSON',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete: function(){
                $('.contaninerLoading').hide(); 
            },
            success: function(data){
                if(data.status === 1){
                    $('#confirmDelete').modal('hide');
                    msgNotification(data.type, data.msg);
                    let table = $('.table-stundents').DataTable();
                    table.ajax.reload();
                }
            },
            error: function (xhr,textStatus,thrownError) {
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });
    });

});

</script>
@stop  

resources/views/admin/students/my_courses.blade.php
@extends('adminlte::page')
@section('title', 'Admin')
@section('content_header')
<div class="row mb-2">
    <div class="col-sm-6">
        <h1><i class="fas fa-award" style="margin:10px 10px 10px 10px;"></i>{{trans('adminlte::students.my_courses')}}</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">{{trans('adminlte::adminlte.dashboard')}}</a></li>
            <li class="breadcrumb-item active">{{trans('adminlte::students.my_courses')}}</li>
        </ol>
    </div>
</div>
@stop
@section('content')
<div class="row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-bordered dt-responsive table-head-fixed">
                            <thead>
                                <tr>
                                    <th>{{trans('adminlte::courses.code')}}</th>
                                    <th>{{trans('adminlte::adminlte.name')}}</th>
                                    <th>{{trans('adminlte::courses.schedule')}}</th>
                                    <th>{{trans('adminlte::courses.frequency')}}</th>      
                                    <th>{{trans('adminlte::inscriptions.inscription')}}</th>                                  
                                    <th>{{trans('adminlte::adminlte.status')}}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(Auth::user()->registration->count() > 0)
                                    @foreach(Auth::user()->registration as $course)
                                        <tr>
                                            <td>{{$course->course->code}}</td>
                                            <td>{{$course->course->service->name}}</td>
                                            <td>
                                                @php
                                                    $start_time = $course->course->start_time ? \Carbon\Carbon::parse($course->course->start_time)->format('g:iA') : NULL;
                                                    $end_time = $course->course->end_time ? \Carbon\Carbon::parse($course->course->end_time)->format('g:iA') : NULL;
                                                @endphp
                                                {{$start_time}} - {{$end_time}}
                                            </td>
                                            <td>
                                                @if($course->course->array_frequency())
                                                   @foreach($course->course->array_frequency() as $day)
                                                        <span class="badge badge-success">{{$day}}</span>
                                                    @endforeach
                                                @endif                                    
                                            </td>   
                                            <td>{{\Carbon\Carbon::parse($course->created_at)->format('d/m/Y')}}</td>
                                            <td>
                                                @if($course->status)                        
                                                    <span class="badge badge-success">{{trans('adminlte::adminlte.active')}}</span>
                                                @else
                                                    <span class="badge badge-danger">{{trans('adminlte::adminlte.inactive')}}</span>
                                                @endif                    
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                <tr>
                                    <td colspan="6">Aun no se encuentran cursos...</td>
                                </tr>
                                @endif
                            </tbody>
                        </table>                        
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>
@stop