routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect("/dashboard");
});

Route::get('/home', function () {
    return redirect("/dashboard");
});

Route::get('dashboard', 'AdminController@index')->name('admin');

Auth::routes();

// setea ruta formulario login
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard'],function(){ 
    Route::get('profile','Users\UsersController@profile')->name('users.profile');
    Route::post('profile/update','Users\UsersController@save_profile')->name('users.profile.update');
});

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard/admin'],function(){  
    Route::resource('roles', 'Roles\RolesController');
    Route::put('roles/ajax/edit','Roles\RolesController@edit')->name('roles.ajax.edit');
    Route::put('roles/ajax/update','Roles\RolesController@update')->name('roles.ajax.update');
    Route::put('roles/ajax/delete','Roles\RolesController@destroy')->name('roles.ajax.delete');
    Route::resource('users', 'Users\UsersController');
    Route::put('users/ajax/edit','Users\UsersController@edit')->name('users.ajax.edit');
    Route::put('users/ajax/update','Users\UsersController@update')->name('users.ajax.update');
    Route::put('users/ajax/delete','Users\UsersController@destroy')->name('users.ajax.delete');
    Route::post('image-view','Users\UsersController@image_store');
    Route::get('avatar/{id}','Users\UsersController@avatar')->name('users.avatar');
    Route::get('configurations','Config\ConfigController@index')->name('configurations');
    Route::put('configurations/ajax/update','Config\ConfigController@update')->name('configurations.ajax.update');
    Route::put('configurations/ajax/updatePayments','Config\ConfigController@updatePayments')->name('configurations.ajax.updatePayments');
    Route::get('configurations/avatar/{id}','Config\ConfigController@avatar')->name('configurations.avatar');
    Route::put('configurations/ajax/exec/payments/process','Config\ConfigController@exec_payments_process')->name('configurations.ajax.exec_payments_process');
    Route::put('configurations/ajax/exec/overdue/payments/process','Config\ConfigController@exec_overdue_payments_process')->name('configurations.ajax.exec_overdue_payments_process');    
    Route::put('configurations/ajax/exec/instructors/payment/process','Config\ConfigController@exec_instructors_payment_process')->name('configurations.ajax.exec_instructors_payment_process');    
    Route::resource('services', 'Services\ServicesController');
    Route::put('services/ajax/edit','Services\ServicesController@edit')->name('services.ajax.edit');
    Route::put('services/ajax/update','Services\ServicesController@update')->name('services.ajax.update');
    Route::put('services/ajax/delete','Services\ServicesController@destroy')->name('services.ajax.delete');
    Route::put('services/ajax/types','Services\ServicesController@get_tbl_types')->name('services.ajax.table_types');
    Route::put('services/ajax/types/store','Services\ServicesController@store_type')->name('services.ajax.store_type');    
    Route::put('services/ajax/levels','Services\ServicesController@get_tbl_levels')->name('services.ajax.table_levels'); 
    Route::put('services/ajax/levels/store','Services\ServicesController@store_level')->name('services.ajax.store_level');
    Route::put('services/ajax/update/status','Services\ServicesController@update_status')->name('services.ajax.update_status');    
    Route::put('services/ajax/delete/type/level','Services\ServicesController@delete_type_or_level')->name('services.ajax.delete_type_or_level');    
    Route::resource('students','Students\StudentsController');
    Route::put('students/ajax/edit','Students\StudentsController@edit')->name('students.ajax.edit');
    Route::put('students/ajax/update','Students\StudentsController@update')->name('students.ajax.update');
    Route::put('students/ajax/delete','Students\StudentsController@destroy')->name('students.ajax.delete');
    Route::resource('instructors','Instructors\InstructorsController');
    Route::put('instructors/ajax/edit','Instructors\InstructorsController@edit')->name('instructors.ajax.edit');
    Route::put('instructors/ajax/update','Instructors\InstructorsController@update')->name('instructors.ajax.update');
    Route::put('instructors/ajax/delete','Instructors\InstructorsController@destroy')->name('instructors.ajax.delete');     
    Route::resource('courses','Courses\CoursesController');
    Route::put('courses/ajax/edit','Courses\CoursesController@edit')->name('courses.ajax.edit');
    Route::put('courses/ajax/update','Courses\CoursesController@update')->name('courses.ajax.update');
    Route::put('courses/ajax/delete','Courses\CoursesController@destroy')->name('courses.ajax.delete');
    Route::put('courses/ajax/calcule/time','Courses\CoursesController@update_end_time')->name('courses.ajax.update_end_time');
    Route::put('inscriptions/ajax/index','Inscriptions\InscriptionsController@index')->name('inscriptions.ajax.index');
    Route::put('inscriptions/ajax/edit','Inscriptions\InscriptionsController@edit')->name('inscriptions.ajax.edit');
    Route::put('inscriptions/ajax/update','Inscriptions\InscriptionsController@update')->name('inscriptions.ajax.update');
    Route::put('inscriptions/ajax/delete','Inscriptions\InscriptionsController@destroy')->name('inscriptions.ajax.delete');
    Route::put('inscriptions/ajax/student','Inscriptions\InscriptionsController@info_student')->name('inscriptions.ajax.info_student');
    Route::put('inscriptions/ajax/student/inscribe','Inscriptions\InscriptionsController@inscribe')->name('inscriptions.ajax.inscribe');
    Route::put('inscriptions/ajax/table/registration','Inscriptions\InscriptionsController@table_registration')->name('inscriptions.ajax.table_registration');
    //payments
    Route::get('payments','Payments\PaymentsController@index')->name('payments.index'); 
    Route::put('payments/courses','Payments\PaymentsController@get_courses_student')->name('payments.ajax.get_courses_student');
    Route::put('payments/info/course','Payments\PaymentsController@info_course')->name('payments.ajax.info_course');
    Route::put('payments/save','Payments\PaymentsController@store')->name('payments.ajax.store');    
    Route::put('payments/total','Payments\PaymentsController@get_total')->name('payments.ajax.get_total');    
    Route::put('payments/add/payment','Payments\PaymentsController@add_new_payment')->name('payments.ajax.add_new_payment');    
    Route::put('payments/add/payment/courses','Payments\PaymentsController@get_courses_student_new_payment')->name('payments.ajax.get_courses_student_new_payment');    
    Route::put('payments/add/payment/courses/cash/value','Payments\PaymentsController@info_value_cash_new_payment')->name('payments.ajax.info_value_cash_new_payment');        
    Route::put('payments/save/payment','Payments\PaymentsController@store_new_payment')->name('payments.ajax.store_new_payment');             
    Route::get('payments/view/all/','Payments\PaymentsController@index_payments')->name('payments.index_payments'); 
    Route::get('payments/export/excel/{status?}/{concept?}/{start_date?}/{end_date?}','Payments\PaymentsController@export_excel')->name('payments.export.excel');     
    //jobs
    Route::get('jobs/process/payments/monthly_payments','Jobs\JobsController@monthly_payments_process')->name('jobs.monthly_payments_process'); 
    Route::get('files/display/{id}','Users\UsersController@display_file')->name('display_file'); 
});

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard/student'],function(){    
    Route::get('courses','Students\StudentsController@my_courses')->name('students.my_courses');
    Route::get('payments','Students\StudentsController@my_payments')->name('students.my_payments');
    Route::post('paypal/payment','Payments\Paypal\PaypalController@paypal_payment')->name('students.paypal_payment');
    Route::get('paypal/payment/status','Payments\Paypal\PaypalController@paypal_payment_status')->name('students.paypal_payment_status');
});

resources/views/admin/instructors/create.blade.php
{{csrf_field()}}
<div class="row">
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="name" class="control-label">{{trans('adminlte::adminlte.name')}}<span class="kv-reqd">*</span></label>
        <input type="text" id="name" class="form-control" maxlength="190" name="name" placeholder="{{trans('adminlte::adminlte.name')}}">
    </div>
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="lastName" class="control-label">{{trans('adminlte::students.lastName')}}</label>
        <input type="text" id="lastName" class="form-control" maxlength="190" name="lastName" placeholder="{{trans('adminlte::students.lastName')}}">
    </div>
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="email" class="control-label">{{trans('adminlte::adminlte.email')}}<span class="kv-reqd">*</span></label>
        <input type="email" id="email" class="form-control" maxlength="190" name="email" placeholder="{{trans('adminlte::adminlte.email')}}">
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="phone" class="control-label">{{trans('adminlte::adminlte.phone')}}</label>
        <input type="text" id="phone" class="form-control" maxlength="190" name="phone" placeholder="{{trans('adminlte::adminlte.phone')}}">
    </div>
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="address" class="control-label">{{trans('adminlte::adminlte.direction')}}</label>
        <input type="text" id="address" class="form-control" minlength="8" maxlength="190" name="address" placeholder="{{trans('adminlte::adminlte.direction')}}">
    </div>
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="status" class="control-label">{{trans('adminlte::adminlte.status')}}<span class="kv-reqd">*</span></label>
        <select id="status" name="status" class="form-control select2 select2-hidden-accessible" style="width: 100%;">
            <option value=""></option>
            <option value="1">{{trans('adminlte::adminlte.active')}}</option>
            <option value="0">{{trans('adminlte::adminlte.inactive')}}</option>
        </select>
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <label for="observations" class="control-label">{{trans('adminlte::adminlte.observations')}}</label>
        <textarea id="observations" class="form-control" rows="3" maxlength="5000" name="observations"></textarea>
    </div>
</div>
<div class="row">    
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-bordered">
            <thead>                  
                <tr>
                    <th>{{trans('adminlte::adminlte.file')}}</th>
                    <th><i class="fas fa-paperclip"></i></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Anexo</td>
                    <td><input type="file" id="anexo" class="form-control-file" name="anexo"></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

resources/views/admin/instructors/edit.blade.php
{{csrf_field()}}
{{ method_field('PUT') }}
<input type="hidden" name="id" id="id" value="{{$user->id}}">
<div class="row">
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="name" class="control-label">{{trans('adminlte::adminlte.name')}}<span class="kv-reqd">*</span></label>
        <input type="text" value="{{$user->name}}" id="name" class="form-control" maxlength="190" name="name" placeholder="{{trans('adminlte::adminlte.name')}}">
    </div>
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="lastName" class="control-label">{{trans('adminlte::instructors.lastName')}}</label>
        <input type="text" value="{{$user->last_name}}" id="lastName" class="form-control" maxlength="190" name="lastName" placeholder="{{trans('adminlte::instructors.lastName')}}">
    </div>
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="email" class="control-label">{{trans('adminlte::adminlte.email')}}<span class="kv-reqd">*</span></label>
        <input type="email" value="{{$user->email}}" id="email" class="form-control" maxlength="190" name="email" placeholder="{{trans('adminlte::adminlte.email')}}">
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="phone" class="control-label">{{trans('adminlte::adminlte.phone')}}</label>
        <input type="text" value="{{$user->phone_number}}" id="phone" class="form-control" maxlength="190" name="phone" placeholder="{{trans('adminlte::adminlte.phone')}}">
    </div>
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="address" class="control-label">{{trans('adminlte::adminlte.direction')}}</label>
        <input type="text" value="{{$user->address}}" id="address" class="form-control" minlength="8" maxlength="190" name="address" placeholder="{{trans('adminlte::adminlte.direction')}}">
    </div>
    <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label for="status" class="control-label">{{trans('adminlte::adminlte.status')}}<span class="kv-reqd">*</span></label>
        <select id="status" name="status" class="form-control select2 select2-hidden-accessible" style="width: 100%;">
            <option value=""></option>
            <option @if($user->status == 1) selected="selected" @endif value="1">{{trans('adminlte::adminlte.active')}}</option>
            <option @if($user->status == 0) selected="selected" @endif value="0">{{trans('adminlte::adminlte.inactive')}}</option>
        </select>
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <label for="observations" class="control-label">{{trans('adminlte::adminlte.observations')}}</label>
        <textarea id="observations" class="form-control" rows="3" maxlength="5000" name="observations">{{$user->observations}}</textarea>
    </div>
</div>
@if(array_key_exists('3',$files) || \App\Models\File_type::find(3)->status == 1)
    <div class="row">    
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="cursos-tab" data-toggle="tab" href="#tabCursos" role="tab" aria-controls="tabCursos" aria-selected="false">{{trans('adminlte::courses.courses')}}</a>
                </li>   
                <li class="nav-item">
                    <a class="nav-link" id="files-tab" data-toggle="tab" href="#tabFiles" role="tab" aria-controls="tabFiles" aria-selected="false">{{trans('adminlte::adminlte.files')}}</a>
                </li>       
            </ul>            
            <div class="tab-content">
                <div class="tab-pane active" id="tabCursos" role="tabpanel" aria-labelledby="cursos-tab">
                    <div class="card-body table-responsive p-0" id="table_cash_register" style="height:200px;">
                        <table class="table table-bordered dt-responsive table-head-fixed">
                            <thead>
                                <tr>
                                    <th>{{trans('adminlte::courses.code')}}</th>
                                    <th>{{trans('adminlte::adminlte.name')}}</th>
                                    <th>{{trans('adminlte::courses.schedule')}}</th>
                                    <th>{{trans('adminlte::courses.frequency')}}</th>                                      
                                    <th>{{trans('adminlte::adminlte.status')}}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if($user->courses->count() > 0)
                                    @foreach($user->courses as $course)
                                        <tr>
                                            <td>{{$course->code}}</td>
                                            <td>{{$course->service->name}}</td>
                                            <td>
                                                @php
                                                    $start_time = $course->start_time ? \Carbon\Carbon::parse($course->start_time)->format('g:iA') : NULL;
                                                    $end_time = $course->end_time ? \Carbon\Carbon::parse($course->end_time)->format('g:iA') : NULL;
                                                @endphp
                                                {{$start_time}} - {{$end_time}}
                                            </td>
                                            <td>
                                                @if($course->array_frequency())
                                                   @foreach($course->array_frequency() as $day)
                                                        <span class="badge badge-success">{{$day}}</span>
                                                    @endforeach
                                                @endif                                    
                                            </td>   
                                            <td>
                                                @if($course->status)                        
                                                    <span class="badge badge-success">{{trans('adminlte::adminlte.active')}}</span>
                                                @else
                                                    <span class="badge badge-danger">{{trans('adminlte::adminlte.inactive')}}</span>
                                                @endif                    
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                <tr>
                                    <td colspan="6">Aun no tiene cursos asignados...</td>
                                </tr>
                                @endif
                            </tbody>
                        </table>                    
                    </div>
                </div>
                <div class="tab-pane" id="tabFiles" role="tabpanel" aria-labelledby="files-tab">
                    <table class="table table-bordered">
                        <thead>                  
                            <tr>
                                <th>{{trans('adminlte::adminlte.file')}}</th>
                                <th><i class="fas fa-paperclip"></i></th>
                                <th><i class="fas fa-file-upload"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{trans('adminlte::instructors.annexed')}}</td>
                                <td>
                                    <a target="_blank" href="@if(array_key_exists('3',$files) && $files[3]['id']) {{$files[3]['file_url']}} @endif" class="" name="curp_student" id="curp_student">@if(array_key_exists('3',$files) && $files[3]['file_name']) {{$files[3]['file_name']}} @endif</a>
                                </td>
                                <td>
                                    @if(\App\Models\File_type::find(3)->status == 1)
                                        <input type="file" id="anexo_instructor" class="form-control-file" name="anexo_instructor">
                                    @endif
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/admin/instructors/index.blade.php
@extends('adminlte::page')
@section('title',trans('adminlte::instructors.instructors'))
@section('content_header')
<div class="row mb-2">
    <div class="col-sm-6">
        <h1><i class="fas fa-chalkboard-teacher" style="margin:10px 10px 10px 10px;"></i>{{trans('adminlte::instructors.instructors')}}</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">{{trans('adminlte::adminlte.administration')}}</a></li>
            <li class="breadcrumb-item active">{{trans('adminlte::instructors.instructors')}}</li>
        </ol>
    </div>
</div>
@stop
@section('content')
<div class="card">
    <div class="card-header">
        <div class="card-title">
            @if($permits['create'])
                <a href="#" class="btn btn-block btn-success btnModalCreate" data-toggle="modal">{{trans('adminlte::adminlte.create')}}</a>
            @endif
        </div>
    </div>
    <div class="card-body">
        {!! $html->table(['class' => 'table table-striped table-bordered dt-responsive table-instructor', 'style' => 'width:100%']) !!}
    </div>
</div>
<div class="modal fade" id="modal-create-instructor" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-gradient-info disabled color-palette">
                <h5 class="modal-title"><i class="fa fa-chalkboard-teacher"></i> {{trans('adminlte::instructors.createInstructor')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form id="frm-crate-instructor" name="frm-crate-instructor" enctype="multipart/form-data">
                <div class="modal-body" id="content-create-instructor"></div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" id="btn-save-instructor" name="btn-save-instructor" class="btn btn-success">{{trans('adminlte::adminlte.save')}}</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<div class="modal fade" id="modal-edit-instructor" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-gradient-info disabled color-palette">
                <h5 class="modal-title"><i class="fa fa-chalkboard-teacher"></i> {{trans('adminlte::instructors.editInstructor')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form id="frm-edit-instructor" name="frm-edit-instructor" enctype="multipart/form-data">
                <div class="modal-body" id="content-edit-instructor"></div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" id="btn-save-edit-instructor" name="btn-save-edit-instructor" class="btn btn-success">{{trans('adminlte::adminlte.save')}}</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@stop
@section('js')
{!! $html->scripts() !!}
<script>
_token = "{{csrf_token()}}";
_method = "PUT";
$(function () {
    
    $(".btnModalCreate").click(function(){
        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url: "{{route('instructors.create')}}",
            type:'GET',
            cache:false,
            data:{'_token':_token,'_method':_method},
            datatype:'JSON',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete:function(){
                $('.contaninerLoading').hide(); 
            },
            success:function(data){
                if(data.status !== 1){
                    ctlErrorRequestAjax(data);
                }//if
                else{
                    $("#content-create-instructor").html(data.html);
                    $('.select2').select2();
                    $('#modal-create-instructor').modal('show');
                }//else
            },
            error:function(xhr,textStatus,thrownError){
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });       
    });
    
    $('#frm-crate-instructor').submit(function(e){
        
        e.preventDefault();
        
        var formData = new FormData(this);
                
        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url:"{{route('instructors.store')}}",
            type:'POST',
            data:formData,
            cache:false,
            contentType:false,
            processData:false,
            datatype:'JSON',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete: function(){
                $('.contaninerLoading').hide(); 
            },
            success: function(data){                                
                if(data.status === 1){
                    $('#modal-create-instructor').modal('hide');
                    msgNotification(data.type, data.msg);
                    let table = $('.table-instructor').DataTable();
                    table.ajax.reload();
                }else{
                    ctlErrorRequestAjax(data);
                }
            },
            error: function (xhr,textStatus,thrownError) {
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });
    }); 

    $(document).on('click','.btnModalEdit',function(){

        var _token = "{{csrf_token()}}";
        var _method = "PUT";
        var id = $(this).data('id');

        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url: "{{route('instructors.ajax.edit')}}",
            type:'POST',
            cache:false,
            data:{'_id':id,'_token':_token,'_method':_method},
            datatype:'html',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete: function(){
                $('.contaninerLoading').hide(); 
            },
            success:function(data){
                $("#content-edit-instructor").html(data);
                $('.select2').select2();
                $('#modal-edit-instructor').modal('show');
            },
            error:function(xhr,textStatus,thrownError){
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });       
    });

    $('#frm-edit-instructor').submit(function(e){
        
        e.preventDefault();
        
        var formData = new FormData(this);
        
        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url:"{{route('instructors.ajax.update')}}",
            type:'POST',
            data:formData,
            cache:false,
            contentType:false,
            processData:false,
            datatype:'JSON',
            beforeSend:function(){
            $('.contaninerLoading').show();
            },
            complete: function(){
            $('.contaninerLoading').hide(); 
            },
            success: function(data){
                if(data.status === 1){
                    $('#modal-edit-instructor').modal('hide');
                    msgNotification(data.type,data.msg);
                    let table = $('.table-instructor').DataTable();
                    table.ajax.reload();
                }
                else{
                    ctlErrorRequestAjax(data);
                }
            },
            error: function (xhr,textStatus,thrownError) {
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });
    }); 
    
    // Confirm delete
    $('.deleteForm').click(function(){

        let _token = "{{csrf_token()}}";
        let _method = "PUT";
        let id = $('#idDelete').val();

        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content') },
            url: "{{route('instructors.ajax.delete')}}",
            type: 'POST',
            cache: false,
            data:{id:id,'_token':_token,'_method':_method},
            datatype: 'JSON',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete: function(){
                $('.contaninerLoading').hide(); 
            },
            success: function(data){
                if(data.status === 1){
                    $('#confirmDelete').modal('hide');
                    msgNotification(data.type, data.msg);
                    let table = $('.table-instructor').DataTable();
                    table.ajax.reload();
                }
            },
            error: function (xhr,textStatus,thrownError) {
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });
    });

});

</script>
@stop  