routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect("/dashboard");
});

Route::get('/home', function () {
    return redirect("/dashboard");
});

Route::get('dashboard', 'AdminController@index')->name('admin');

Auth::routes();

// setea ruta formulario login
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard'],function(){ 
    Route::get('profile','Users\UsersController@profile')->name('users.profile');
    Route::post('profile/update','Users\UsersController@save_profile')->name('users.profile.update');
});

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard/admin'],function(){  
    Route::resource('roles', 'Roles\RolesController');
    Route::put('roles/ajax/edit','Roles\RolesController@edit')->name('roles.ajax.edit');
    Route::put('roles/ajax/update','Roles\RolesController@update')->name('roles.ajax.update');
    Route::put('roles/ajax/delete','Roles\RolesController@destroy')->name('roles.ajax.delete');
    Route::resource('users', 'Users\UsersController');
    Route::put('users/ajax/edit','Users\UsersController@edit')->name('users.ajax.edit');
    Route::put('users/ajax/update','Users\UsersController@update')->name('users.ajax.update');
    Route::put('users/ajax/delete','Users\UsersController@destroy')->name('users.ajax.delete');
    Route::post('image-view','Users\UsersController@image_store');
    Route::get('avatar/{id}','Users\UsersController@avatar')->name('users.avatar');
    Route::get('configurations','Config\ConfigController@index')->name('configurations');
    Route::put('configurations/ajax/update','Config\ConfigController@update')->name('configurations.ajax.update');
    Route::put('configurations/ajax/updatePayments','Config\ConfigController@updatePayments')->name('configurations.ajax.updatePayments');
    Route::get('configurations/avatar/{id}','Config\ConfigController@avatar')->name('configurations.avatar');
    Route::put('configurations/ajax/exec/payments/process','Config\ConfigController@exec_payments_process')->name('configurations.ajax.exec_payments_process');
    Route::put('configurations/ajax/exec/overdue/payments/process','Config\ConfigController@exec_overdue_payments_process')->name('configurations.ajax.exec_overdue_payments_process');    
    Route::put('configurations/ajax/exec/instructors/payment/process','Config\ConfigController@exec_instructors_payment_process')->name('configurations.ajax.exec_instructors_payment_process');    
    Route::resource('services', 'Services\ServicesController');
    Route::put('services/ajax/edit','Services\ServicesController@edit')->name('services.ajax.edit');
    Route::put('services/ajax/update','Services\ServicesController@update')->name('services.ajax.update');
    Route::put('services/ajax/delete','Services\ServicesController@destroy')->name('services.ajax.delete');
    Route::put('services/ajax/types','Services\ServicesController@get_tbl_types')->name('services.ajax.table_types');
    Route::put('services/ajax/types/store','Services\ServicesController@store_type')->name('services.ajax.store_type');    
    Route::put('services/ajax/levels','Services\ServicesController@get_tbl_levels')->name('services.ajax.table_levels'); 
    Route::put('services/ajax/levels/store','Services\ServicesController@store_level')->name('services.ajax.store_level');
    Route::put('services/ajax/update/status','Services\ServicesController@update_status')->name('services.ajax.update_status');    
    Route::put('services/ajax/delete/type/level','Services\ServicesController@delete_type_or_level')->name('services.ajax.delete_type_or_level');    
    Route::resource('students','Students\StudentsController');
    Route::put('students/ajax/edit','Students\StudentsController@edit')->name('students.ajax.edit');
    Route::put('students/ajax/update','Students\StudentsController@update')->name('students.ajax.update');
    Route::put('students/ajax/delete','Students\StudentsController@destroy')->name('students.ajax.delete');
    Route::resource('instructors','Instructors\InstructorsController');
    Route::put('instructors/ajax/edit','Instructors\InstructorsController@edit')->name('instructors.ajax.edit');
    Route::put('instructors/ajax/update','Instructors\InstructorsController@update')->name('instructors.ajax.update');
    Route::put('instructors/ajax/delete','Instructors\InstructorsController@destroy')->name('instructors.ajax.delete');     
    Route::resource('courses','Courses\CoursesController');
    Route::put('courses/ajax/edit','Courses\CoursesController@edit')->name('courses.ajax.edit');
    Route::put('courses/ajax/update','Courses\CoursesController@update')->name('courses.ajax.update');
    Route::put('courses/ajax/delete','Courses\CoursesController@destroy')->name('courses.ajax.delete');
    Route::put('courses/ajax/calcule/time','Courses\CoursesController@update_end_time')->name('courses.ajax.update_end_time');
    Route::put('inscriptions/ajax/index','Inscriptions\InscriptionsController@index')->name('inscriptions.ajax.index');
    Route::put('inscriptions/ajax/edit','Inscriptions\InscriptionsController@edit')->name('inscriptions.ajax.edit');
    Route::put('inscriptions/ajax/update','Inscriptions\InscriptionsController@update')->name('inscriptions.ajax.update');
    Route::put('inscriptions/ajax/delete','Inscriptions\InscriptionsController@destroy')->name('inscriptions.ajax.delete');
    Route::put('inscriptions/ajax/student','Inscriptions\InscriptionsController@info_student')->name('inscriptions.ajax.info_student');
    Route::put('inscriptions/ajax/student/inscribe','Inscriptions\InscriptionsController@inscribe')->name('inscriptions.ajax.inscribe');
    Route::put('inscriptions/ajax/table/registration','Inscriptions\InscriptionsController@table_registration')->name('inscriptions.ajax.table_registration');
    //payments
    Route::get('payments','Payments\PaymentsController@index')->name('payments.index'); 
    Route::put('payments/courses','Payments\PaymentsController@get_courses_student')->name('payments.ajax.get_courses_student');
    Route::put('payments/info/course','Payments\PaymentsController@info_course')->name('payments.ajax.info_course');
    Route::put('payments/save','Payments\PaymentsController@store')->name('payments.ajax.store');    
    Route::put('payments/total','Payments\PaymentsController@get_total')->name('payments.ajax.get_total');    
    Route::put('payments/add/payment','Payments\PaymentsController@add_new_payment')->name('payments.ajax.add_new_payment');    
    Route::put('payments/add/payment/courses','Payments\PaymentsController@get_courses_student_new_payment')->name('payments.ajax.get_courses_student_new_payment');    
    Route::put('payments/add/payment/courses/cash/value','Payments\PaymentsController@info_value_cash_new_payment')->name('payments.ajax.info_value_cash_new_payment');        
    Route::put('payments/save/payment','Payments\PaymentsController@store_new_payment')->name('payments.ajax.store_new_payment');             
    Route::get('payments/view/all/','Payments\PaymentsController@index_payments')->name('payments.index_payments'); 
    Route::get('payments/export/excel/{status?}/{concept?}/{start_date?}/{end_date?}','Payments\PaymentsController@export_excel')->name('payments.export.excel');     
    //jobs
    Route::get('jobs/process/payments/monthly_payments','Jobs\JobsController@monthly_payments_process')->name('jobs.monthly_payments_process'); 
    Route::get('files/display/{id}','Users\UsersController@display_file')->name('display_file'); 
});

Route::group(['middleware'=>['auth'],'prefix'=>'dashboard/student'],function(){    
    Route::get('courses','Students\StudentsController@my_courses')->name('students.my_courses');
    Route::get('payments','Students\StudentsController@my_payments')->name('students.my_payments');
    Route::post('paypal/payment','Payments\Paypal\PaypalController@paypal_payment')->name('students.paypal_payment');
    Route::get('paypal/payment/status','Payments\Paypal\PaypalController@paypal_payment_status')->name('students.paypal_payment_status');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Caffeinated\Shinobi\Concerns\HasRolesAndPermissions;
use OwenIt\Auditing\Contracts\Auditable;

class User extends Authenticatable implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    
    use Notifiable;
    use HasRolesAndPermissions;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id','name','last_name','email','phone_number','address','password','observations','avatar','type_user','status','last_login_at','last_login_ip'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    public function adminlte_image(){
        return route('users.avatar',['id'=>$this->id]).'?'.time();
    }
    
    public function tutor(){
        return $this->hasOne(\App\Models\Tutor::class);
    }
    
    public function user_files(){
        return $this->hasMany(\App\Models\User_file::class,'user_id','id');
    }
    
    public function registration(){
        return $this->hasMany(\App\Models\Student_registration::class,'user_id','id');
    }
    
    public function active_registration(){
        return $this->hasMany(\App\Models\Student_registration::class,'user_id','id')->where('student_registrations.status',1);
    }
    
    public function courses(){
        return $this->hasMany(\App\Models\Course::class,'user_id','id');
    }
    
    public function active_courses(){
        return $this->hasMany(\App\Models\Course::class,'user_id','id')->where('courses.status',1);
    }
    
    public function payments(){
        return $this->hasMany(\App\Models\Payment::class,'user_id','id')->orderBy('id','DESC');
    }
    
    public function pending_payments(){
        return $this->hasMany(\App\Models\Payment::class,'user_id','id')->where('payments.status_id',1)->orderBy('id','DESC');
    } 

    public function records_payments(){
        return $this->hasMany(\App\Models\Payment::class,'user_id','id')->where('payments.status_id','<>',1)->orderBy('id','DESC');
    }     
            
    public function admin_payments_detail(){
        return $this->hasMany(\App\Models\Payment_detail::class,'admin_id','id');
    }
    
    public function name(){
        return $this->name.($this->last_name ? ' '.$this->last_name : '');
    }
}

resources/views/admin/users/create.blade.php
<div class="row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <label for="roles[]" class="control-label">{{trans('adminlte::adminlte.roles')}}<span class="kv-reqd">*</span></label>
        <select name="roles[]" id="roles" class="form-control select2" multiple="multiple" data-placeholder="{{trans("adminlte::roles.selectRoles")}}"  style="width:100%;">
        @foreach(\App\Models\Role::all() as $role)
            <option value="{{$role->slug}}">{{ $role->name}}</option>
        @endforeach
        </select>
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <label for="name" class="control-label">{{trans('adminlte::adminlte.name')}}<span class="kv-reqd">*</span></label>
        <input type="text" id="name" class="form-control" maxlength="190" name="name" placeholder="{{trans('adminlte::adminlte.name')}}">
    </div>
    <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <label for="email" class="control-label">{{trans('adminlte::adminlte.email')}}<span class="kv-reqd">*</span></label>
        <input type="text" id="email" class="form-control" maxlength="190" name="email" placeholder="{{trans('adminlte::adminlte.email')}}">
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <label for="password" class="control-label">{{trans('adminlte::adminlte.password')}}<span class="kv-reqd">*</span></label>
        <input type="password" id="password" class="form-control" minlength="8" maxlength="255" name="password" placeholder="{{trans('adminlte::adminlte.password')}}">
    </div>
    <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <label for="password_confirmation" class="control-label">{{trans('adminlte::adminlte.confirm_password')}}<span class="kv-reqd">*</span></label>
        <input type="password" id="password_confirmation" class="form-control" minlength="8" maxlength="255" name="password_confirmation" placeholder="{{trans('adminlte::adminlte.confirm_password')}}">
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <label for="description" class="control-label">{{trans('adminlte::adminlte.observations')}}</label>
        <textarea id="description" class="form-control" rows="3" maxlength="1000" name="description"></textarea>
    </div>
</div>

resources/views/admin/users/edit.blade.php
<input type="hidden" name="id" id="id" value="{{$user->id}}">
<div class="row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <label for="roles_user[]" class="control-label">{{trans('adminlte::adminlte.roles')}}<span class="kv-reqd">*</span></label>
        <select name="roles_user[]" id="roles_user" class="form-control select2" multiple="multiple" data-placeholder="{{trans("adminlte::roles.selectRoles")}}"  style="width:100%;">
        @foreach(\App\Models\Role::all() as $role)
            <option @if($user->hasRole($role->slug))  selected="selected" @endif value="{{$role->slug}}">{{ $role->name}}</option>
        @endforeach
        </select>
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <label for="name_user" class="control-label">{{trans('adminlte::adminlte.name')}}<span class="kv-reqd">*</span></label>
        <input type="text" id="name_user" class="form-control" maxlength="190" name="name_user" value="{{$user->name}}" placeholder="{{trans('adminlte::adminlte.name')}}">
    </div>
    <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <label for="email_user" class="control-label">{{trans('adminlte::adminlte.email')}}<span class="kv-reqd">*</span></label>
        <input type="text" id="email_user" class="form-control" maxlength="190" name="email_user" value="{{$user->email}}" placeholder="{{trans('adminlte::adminlte.email')}}">
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <label for="password_user" class="control-label">{{trans('adminlte::adminlte.password')}}</label>
        <input type="password" id="password_user" class="form-control" minlength="8" maxlength="255" name="password_user" placeholder="{{trans('adminlte::adminlte.password')}}">
    </div>
    <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <label for="password_confirmation_user" class="control-label">{{trans('adminlte::adminlte.confirm_password')}}</label>
        <input type="password" id="password_confirmation_user" class="form-control" minlength="8" maxlength="255" name="password_confirmation_user" placeholder="{{trans('adminlte::adminlte.confirm_password')}}">
    </div>
</div>
<div class="row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <label for="description" class="control-label">{{trans('adminlte::adminlte.observations')}}</label>
        <textarea id="description_user" class="form-control" rows="3" maxlength="1000" name="description_user">{{$user->description}}</textarea>
    </div>
</div>

resources/views/admin/users/index.blade.php
@extends('adminlte::page')
@section('title',trans('adminlte::users.users'))
@section('content_header')
<div class="row mb-2">
    <div class="col-sm-6">
        <h1><i class="fas fa-user-friends" style="margin:10px 10px 10px 10px;"></i>{{trans('adminlte::users.users')}}</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">{{trans('adminlte::adminlte.administration')}}</a></li>
            <li class="breadcrumb-item active">{{trans('adminlte::users.users')}}</li>
        </ol>
    </div>
</div>
@stop
@section('content')
<div class="card">
    <div class="card-header">
        <div class="card-title">
            @if($permits['create'])
                <a href="#" class="btn btn-block btn-success btnModalCreate" data-toggle="modal">Crear</a>
            @endif
        </div>
    </div>
    <div class="card-body">
        {!! $html->table(['class' => 'table table-striped table-bordered dt-responsive', 'style' => 'width:100%']) !!}
    </div>
</div>
<div class="modal fade" id="modal-create-user" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-gradient-info disabled color-palette">
                <h5 class="modal-title"><i class="fa fa-user-friends"></i> Crear Usuario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" id="content-create-user"></div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="button" id="btn-save-user" name="btn-save-user" class="btn btn-success">{{trans('adminlte::adminlte.save')}}</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modal-edit-user" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-gradient-info disabled color-palette">
                <h5 class="modal-title"><i class="fa fa-user-friends"></i> Editar Usuario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" id="content-edit-user"></div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="button" id="btn-save-edit-user" name="btn-save-edit-user" class="btn btn-success">{{trans('adminlte::adminlte.save')}}</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@stop
@section('js')
{!! $html->scripts() !!}
<script>
_token = "{{csrf_token()}}";
_method = "PUT";
$(function () {
    
    $(".btnModalCreate").click(function(){
        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url: "{{route('users.create')}}",
            type:'GET',
            cache:false,
            data:{'_token':_token,'_method':_method},
            datatype:'JSON',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete:function(){
                $('.contaninerLoading').hide(); 
            },
            success:function(data){
                if(data.status !== 1){
                    ctlErrorRequestAjax(data);
                }//if
                else{
                    $("#content-create-user").html(data.html);
                    $('.select2').select2();
                    $('#modal-create-user').modal('show');
                }//else
            },
            error:function(xhr,textStatus,thrownError){
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });       
    });
    
    $("#btn-save-user").click(function(){
        
        var roles = $("#roles").val().length ? JSON.stringify($("#roles").val()) : null;
        
        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url:"{{route('users.store')}}",
            type:'POST',
            cache:false,
            data:{roles:roles,name:$("#name").val(),email:$("#email").val(),password:$("#password").val(),password_confirmation:$("#password_confirmation").val(),description:$("#description").val(),'_token':_token},
            datatype:'JSON',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete: function(){
                $('.contaninerLoading').hide(); 
            },
            success: function(data){                                
                if(data.status === 1){
                    $('#modal-create-user').modal('hide');
                    msgNotification(data.type, data.msg);
                    // Se refresca tabla por ajax
                    let table = $('.table').DataTable();
                    table.ajax.reload();
                }else{
                    ctlErrorRequestAjax(data);
                }
            },
            error: function (xhr,textStatus,thrownError) {
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });
    }); 

    $(document).on('click','.btnModalEdit',function(){

        var _token = "{{csrf_token()}}";
        var _method = "PUT";
        var id = $(this).data('id');

        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url: "{{route('users.ajax.edit')}}",
            type:'POST',
            cache:false,
            data:{'_id':id,'_token':_token,'_method':_method},
            datatype:'html',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete: function(){
                $('.contaninerLoading').hide(); 
            },
            success:function(data){
                $("#content-edit-user").html(data);
                $('.select2').select2();
                $('#modal-edit-user').modal('show');
            },
            error:function(xhr,textStatus,thrownError){
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });       
    });

    $(document).on('click','#btn-save-edit-user',function (){

        var _token = "{{csrf_token()}}";
        var _method = "PUT";
        var roles = $("#roles_user").val().length ? JSON.stringify($("#roles_user").val()) : null;
        
        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content')},
            url:"{{route('users.ajax.update')}}",
            type:'POST',
            cache:false,
            data:{'_id':$("#id").val(),roles:roles,name:$("#name_user").val(),email:$("#email_user").val(),password:$("#password_user").val(),password_confirmation:$("#password_confirmation_user").val(),description:$("#description_user").val(),'_token':_token,'_method':_method},
            datatype:'JSON',
            beforeSend:function(){
            $('.contaninerLoading').show();
            },
            complete: function(){
            $('.contaninerLoading').hide(); 
            },
            success: function(data){
                if(data.status === 1){
                    $('#modal-edit-user').modal('hide');
                    msgNotification(data.type,data.msg);
                    // Se refresca tabla por ajax
                    let table = $('.table').DataTable();
                    table.ajax.reload();
                }
                else{
                    ctlErrorRequestAjax(data);
                }
            },
            error: function (xhr,textStatus,thrownError) {
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });
    }); 
    
    // Confirm delete
    $('.deleteForm').click(function(){

        let _token = "{{csrf_token()}}";
        let _method = "PUT";
        let id = $('#idDelete').val();

        $.ajax({
            headers:{'X-CSRF-Token':$('meta[name=_token]').attr('content') },
            url: "{{route('users.ajax.delete')}}",
            type: 'POST',
            cache: false,
            data:{id:id,'_token':_token,'_method':_method},
            datatype: 'JSON',
            beforeSend:function(){
                $('.contaninerLoading').show();
            },
            complete: function(){
                $('.contaninerLoading').hide(); 
            },
            success: function(data){
                if(data.status === 1){
                    $('#confirmDelete').modal('hide');
                    msgNotification(data.type, data.msg);
                    // Se refresca tabla por ajax
                    let table = $('.table').DataTable();
                    table.ajax.reload();
                }
            },
            error: function (xhr,textStatus,thrownError) {
                alert(xhr + "\n" + textStatus + "\n" + thrownError);
            }
        });
    });

});

</script>
@stop  